name: weather_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get_it: ^8.0.3
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  dartz: ^0.10.1
  internet_connection_checker_plus: ^2.7.1
  http: ^1.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  mockito: ^5.4.5

flutter:
  uses-material-design: true

